### PR TITLE
Show user bookings

### PR DESCRIPTION
**Pull request by adklempner**
Requires [#95](https://github.com/windingtree/wt-js-libs/pull/95) in wt-js-libs

### CODE REVIEW

**Comment by AugustoL** [comment]
@adklempner does the bookings work for you?

**Comment by adklempner** [comment]
When I was testing it I was using WTIndex @ `0x2176138a114a7C29bce254Dd9a8e4ADFA8329af6` and it works fine.
Testing it with the WTIndexs in the config I'm running across errors. Will investigate further.

**Comment by adklempner** [comment]
I deployed a fresh WTIndex at `0xaD15Aa12DD0698feD6dA60A1192dB55f5175a388`, set the LifToken to  `0xB6e225194a1C892770c43D4B529841C99b3DA1d7` and everything works

**Comment by AugustoL** [comment]
@adklempner thanks! I forgot to set the LifToken to the new index :grimacing:

**Pull request merged**
