### PR TITLE
UI now addapts to small screens. (Except Explorer)

### PR DESCRIPTION
**Pull request by skkr**
@AugustoL, after merging with master the Explorer is not working. The rwd is ready for all the other sections.

### CODE REVIEW

**Comment by skkr** [comment]
@AugustoL I modified the Hotel Explorer to make it responsive and incorporated the latest changes from master. Let me know if have any comments!

**Comment by AugustoL** [comment]
seleccion_012

Great job @skkr , but can you change the height of the navbar to dont increase in mobile? I cant read the page title if the nav bar is to high. Maybe decrease the font of the nav links in mobile.

**Comment by skkr** [comment]
@AugustoL it was caused by the new menu item. I made some changes to the nav so it looks better and it doesn't break on small screens.

**Comment by AugustoL** [comment]
@skkr thx! it looks awesome! im going to push a fix of the myBookings views and then merge.

**Comment by skkr** [comment]
Excelent! Thanks for the quick feedbak @AugustoL!

**Pull request merged**
